CREATE TABLE POSTS_DEL
(ID_PESSOA    NUMBER(7)      NOT NULL,
 DT_POST      DATE           NOT NULL,
 DS_MENSAGEM  VARCHAR2(4000) NOT NULL,
 DT_CANC      DATE,
 ID_USR_CANC  VARCHAR2(80));
 
ALTER TABLE POSTS_DEL ADD CONSTRAINT PK_POSTS_DEL PRIMARY KEY (ID_PESSOA, DT_POST);

--ALTER TABLE GC.POSTS_DEL ADD CONSTRAINT ID_PESSOA_FK FOREIGN KEY (ID_PESSOA) REFERENCES GC.EQUIPE (ID_PESSOA);
