CREATE TABLE SERVICOS_DEL
(ID_SERVICO  NUMBER(10)     NOT NULL,
 DS_SERVICO   VARCHAR2(100) NOT NULL,
 ID_USR_INCL  VARCHAR2(80)  NOT NULL,
 DT_INCL      DATE          NOT NULL,
 ID_USR_ATLZ  VARCHAR2(80),
 DT_ATLZ      DATE,
 DT_CANC      DATE,
 ID_USR_CANC  VARCHAR2(80));

ALTER TABLE SERVICOS_DEL ADD CONSTRAINT PK_SERVICOS_DEL PRIMARY KEY (ID_SERVICO);
