CREATE OR REPLACE TRIGGER GT_SERVICOS_DEL
                          ------------
 BEFORE INSERT
     OR UPDATE
     ON SERVICOS_DEL     FOR EACH ROW
--
BEGIN
--
-- ARQUIVO...: GT_SERVICOS.sql
-- OBJETIVO..: GATILHO DA GT_SERVICOS_DEL
-- AUTOR/DATA: GUSTAVO.GAIA, 12/02/2022
--
 IF INSERTING
  THEN
  :NEW.ID_USR_INCL := USER;
  :NEW.DT_INCL     := SYSDATE;
 END IF;
--
 IF UPDATING
  THEN
  :NEW.ID_USR_ATLZ := USER;
  :NEW.DT_ATLZ:= SYSDATE;
 END IF;
--
END;
